export const routes = {
  home: '/',
  allFunds: '/all-funds',
  allFundsProfit: '/all-funds/profit',
  fundDetailes: '/all-funds/fund/*',
  fund: '/all-funds/fund',
  tracked: '/tracked',
  trackedProfit: '/tracked/profit',
  data: '/data',
  roles: '/roles',
  events: '/events',
  auth: '/auth',
  authStep2: '/auth/step-2',
  authStep3: '/auth/step-3',
  setupAutoLock: '/setup/autolock',
  authSecondary: '/auth/secondary',
  empty: '',
  notFoundPage: '/404',
  profile: '/profile',
};
